version: "3"
services:
  mysqldb:
    image: mysql:8
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_ROOT_HOST=${DB_HOST}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql

  express:
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
